const notes = [
  {
    id: "n101",
    type: "note-txt",
    isPinned: true,
    info: { txt: "Fullstack Me Baby!" },
  },
  {
    id: "n102",
    type: "note-img",
    info: { url: "http://some-img/me", title: "Bobi and Me" },
    style: { backgroundColor: "#00d" },
  },
  {
    id: "n103",
    type: "note-todos",
    info: {
      label: "Get my stuff together",
      todos: [
        { txt: "Driving liscence", doneAt: null },
        { txt: "Coding power", doneAt: 187111111 },
      ],
    },
  },
]


let notesClasses = () => {
  let classes = []
  for (let i = 0; i < 40; i++) {
    classes.push({ class: getRandomIntInclusive(1, 7), id: makeId() })
  }
  return classes
}

// todo - create an array of 30 objects
// todo - create an object randomly from this array of types [image, text , todo , iframe]
// ? text
// todo - if txt return random lorem ipsum generated by heigth/class 
// todo - check how long the text is and give it a class accordingly ??? hieght  of every line is 24px+-
// todo - make the text appear well in the grid use dynamic text sizing vh prop? 
// ? image
// todo - get images from lorem ipsum
// todo - make any image appear well in the note by giving them a class by width or hieght
// todo - image will be on the top and title will be on yhe bottom of the note
// ? iframe 
// todo - all video have the same dispaly ratio more or less so make the notes of this types all be the same class\
// ? todo
