import { utilService } from "../../../services/util.service.js"
import storageService from "../../../services/storage.service.js"

import { gNotes } from "./notes.data.js"

const { makeId, makeLorem, getRandomIntInclusive, randomBoolean } = utilService
export const noteService = {
  query,
  getById,
  addNoteOrTodo,
  removeNoteOrTodo,
}
console.log(gNotes)
// todo - return to index the array of notes
// todo - save the db to local storage
// todo - make the index display the notes from the storage
// todo - make the note form add a note to the db
// todo - give the note delete function
// todo - style the notes
//
const KEY = "notesDB"

// let notesClasses = () => {
//   let classes = []
//   for (let i = 0; i < 40; i++) {
//     classes.push({ class: getRandomIntInclusive(1, 7), id: makeId() })
//   }
//   return classes
// }

// todo - each note has a color
// todo - each note has a bool isPinned
// todo - create an array of 30 objects
// todo - create an object randomly from this array of types [image, text , todo , iframe]

// ? text
// todo - if txt return random lorem ipsum generated by height/class
// todo - check how long the text is and give it a class accordingly ??? hieght  of every line is 24px+-
// todo - make the text appear well in the grid use dynamic text sizing vh prop?
// ? image
// todo - get images from lorem ipsum
// todo - make any image appear well in the note by giving them a class by width or hieght
// todo - image will be on the top and title will be on yhe bottom of the note
// ? iframe
// todo - all video have the same dispaly ratio more or less so make the notes of this type all be the same class just a different src
// ? todo note
// todo - if type is todo the note sould use the same functionality as an email  = done(read/unread) \ remove \ edit \ add todo

// let keeps = []
// const TYPES = ["text", "todo", "iframe", "img"]
// const NOTE_COUNT = 30

// const _createData = (count) => {
//   for (let i = 0; i < count; i++) {
//     let type =
//     console.log()

//   }
// }

function query(filterBy) {
  let notes = _loadFromStorage(KEY)
  if (!notes) {
    notes = [...gNotes]
    console.log(gNotes)
    _saveToStorage(notes)
  }
  // TODO - add search filter here you can add more functionality like sorting by date or a-z
  // if (filterBy) {
  //   let { isOnSale, title, minPrice, maxPrice } = filterBy
  //   if (isOnSale === "") isOnSale = false
  //   if (!minPrice) minPrice = 0
  //   if (!maxPrice) maxPrice = Infinity
  //   notes = notes.filter((book) => {
  //     if (isOnSale) {
  //       return (
  //         book.listPrice.amount >= minPrice &&
  //         book.listPrice.amount <= maxPrice &&
  //         book.title.includes(title) &&
  //         book.listPrice.isOnSale === isOnSale
  //       )
  //     } else {
  //       return (
  //         book.listPrice.amount >= minPrice &&
  //         book.listPrice.amount <= maxPrice &&
  //         book.title.includes(title)
  //       )
  //     }
  //   })
  // }
  return Promise.resolve(notes)
}

function getById(noteId) {
  if (!noteId) return Promise.resolve(null)
  const notes = _loadFromStorage()
  const note = notes.find((note) => noteId === note.id)
  return Promise.resolve(note)
}

function removeNoteOrTodo(todoId, noteId) {
  let notes = _loadFromStorage()
  notes.map((note) => {
    if (note.id === noteId) {
      let todos = note.todos.filter((todo) => todo.id !== todoId)
      console.log(todos)
      note.todos = todos
      _saveToStorage(notes)
    }
  })
  return Promise.resolve(books)
}

function addNoteOrTodo(noteId, todo) {
  let notes = _loadFromStorage()
  notes.map((note) => {
    if (note.id === noteId) {
      if (!note["todos"]) {
        note["todos"] = [{ ...todo, id: makeId() }]
      } else {
        note["todos"] = [{ ...todo, id: makeId() }, ...note.todos]
      }
    }
  })
  _saveToStorage(notes)
  return Promise.resolve(notes)
}

function _loadFromStorage() {
  return storageService.loadFromStorage(KEY)
}

function _saveToStorage(notes) {
  return storageService.saveToStorage(KEY, notes)
}
